name: Upload Release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: tweaks
          path: .tweaks

      - name: Pack Release
        uses: ThirteenAG/zip-release@master
        with:
          path: ./*
          type: 'zip'
          filename: 'SA.CommunityMapFixes.zip'
          exclusions: '.git .github .tweaks readme.md'
          
      - name: Pack Save Patch
        uses: ThirteenAG/zip-release@master
        with:
          path: .tweaks/save-patch/*
          type: 'zip'
          filename: 'Tweaks.CompatibilityPatch.zip'
          exclusions: '.git .github .main'
          
      - name: Pack Vending Variants
        uses: ThirteenAG/zip-release@master
        with:
          path: .tweaks/vend-variants/*
          type: 'zip'
          filename: 'Tweaks.VendingVariants.zip'
          exclusions: '.git .github .main'
          
      - name: Pack Classic Pickups
        uses: ThirteenAG/zip-release@master
        with:
          path: .tweaks/classic-icons/*
          type: 'zip'
          filename: 'Tweaks.ClassicPickups.zip'
          exclusions: '.git .github .main'
          
      - name: Pack "The Clam Digger" Billboard
        uses: ThirteenAG/zip-release@master
        with:
          path: .tweaks/lcs-billboard/*
          type: 'zip'
          filename: 'Tweaks.LCSBillboard.zip'
          exclusions: '.git .github .main'

      - name: Get Release Info
        id: release_info
        uses: cardinalby/git-get-release-action@1.2.2
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: latest

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ steps.release_info.outputs.name }}
          body: ${{ steps.release_info.outputs.body }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          artifacts: SA.CommunityMapFixes.zip,Tweaks.CompatibilityPatch.zip,Tweaks.VendingVariants.zip,Tweaks.ClassicPickups.zip,Tweaks.LCSBillboard.zip